Gpl 913 housekeeping remove cgap integration
sanger/asset_audits pull request #237
Opened 2021-03-09 08:58 UTC by stevieing

Closes #236 

Changes proposed in this pull request:

*
*
* ...

2021-03-09 09:08 UTC, pjvv approved these changes
There would also be a related deployment change now that I think about it.

Want to include some gem updates?

2021-03-09 09:10 UTC, stevieing commented
> There would also be a related deployment change now that I think about it.
> 
> Want to include some gem updates?

I'll get a few of them done before stand up.

2021-03-17 08:17 UTC, JamesGlover commented on app/controllers/process_plates_controller.rb
This limit was added due to wrangler performance issues, so can also be removed.

2021-03-17 08:38 UTC, JamesGlover commented on app/controllers/process_plates_controller.rb
> -
You're no longer setting @results, but are rendering the results template, which contains:

```haml
# app/views/process_plates/results.html.haml
  %tbody
    - @results.each do |barcode, details|
```

Not sure why this isn't blowing up, so sorry if I missed something. Still, probably makes sense to remove the results render, as the table is always going to be empty.

It used to just:
```
flash[:notice] = 'success'
...
format.html { redirect_to(new_process_plate_path) }
```

Although the new flash (which should be flash.now for a render) definitely looks like an improvement.

2021-03-17 08:43 UTC, JamesGlover requested changes
Couple of potential issues I spotted. I'm not sure why the template problem isn't a noisy one.
The limit can definitely be removed though.

2021-03-17 10:21 UTC, JamesGlover approved these changes

2021-03-18 08:29 UTC, merged